-- Active: 1730687188808@@127.0.0.1@3306@cs_student_graduation_checker

-- Creates Database
DROP DATABASE IF EXISTS CS_Student_Graduation_Checker;
CREATE DATABASE CS_Student_Graduation_Checker;
USE CS_Student_Graduation_Checker;

-- Creates table for student information
CREATE TABLE Students (
    student_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255),
    enrollment_year INT,
    graduation_year INT
);

-- Creates table for course information
CREATE TABLE Courses (
    course_id INT AUTO_INCREMENT PRIMARY KEY,
    course_code VARCHAR(10) UNIQUE NOT NULL,
    course_name VARCHAR(100) NOT NULL,
    credits INT NOT NULL,
    category VARCHAR(50)
);

-- Creates table for information about each student's courses with separate foreign key constraints
CREATE TABLE StudentCourses (
    student_course_id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT,
    course_id INT,
    status VARCHAR(20) NOT NULL,
    grade VARCHAR(2),
    semester VARCHAR(20),
    FOREIGN KEY (student_id) REFERENCES Students(student_id) ON DELETE CASCADE,
    FOREIGN KEY (course_id) REFERENCES Courses(course_id) ON DELETE CASCADE,
    CHECK (status IN ('completed', 'in-progress', 'planned'))
);

-- Creates table for classes required toward completing degree
CREATE TABLE DegreeRequirements (
    requirement_id SERIAL PRIMARY KEY,
    course_id INT NOT NULL,
    requirement_type VARCHAR(50),
    FOREIGN KEY (course_id) REFERENCES Courses(course_id) ON DELETE CASCADE
);

-- Creates table to keep track of student's progress toward graduation
CREATE TABLE Progress (
    student_id INT PRIMARY KEY,
    total_credits_completed INT DEFAULT 0,
    total_percentage_completed DECIMAL(5, 2) DEFAULT 0.00,
    core_credits_remaining INT DEFAULT 0,
    science_credits_remaining INT DEFAULT 0,
    math_credits_remaining INT DEFAULT 0,
    general_ed_credits_remaining INT DEFAULT 0,
    free_elective_credits_remaining INT DEFAULT 0,
    FOREIGN KEY (student_id) REFERENCES Students(student_id) ON DELETE CASCADE
);

INSERT INTO Courses (course_code, course_name, credits, category) VALUES
-- Core Computer Science Courses
('CS 111', 'Program Design I', 3, 'Core'),
('CS 141', 'Program Design II', 3, 'Core'),
('CS 151', 'Mathematical Foundations of Computing', 3, 'Core'),
('CS 211', 'Programming Practicum', 3, 'Core'),
('CS 251', 'Data Structures', 4, 'Core'),
('CS 261', 'Machine Organization', 3, 'Core'),
('CS 301', 'Languages and Automata', 3, 'Core'),
('CS 341', 'Programming Language Design and Implementation', 3, 'Core'),
('CS 342', 'Software Design', 3, 'Core'),
('CS 361', 'Systems Programming', 3, 'Core'),
('CS 362', 'Computer Design', 3, 'Core'),
('CS 377', 'Ethical Issues in Computing', 3, 'Core'),
('CS 401', 'Computer Algorithms I', 3, 'Core'),
('CS 499', 'Professional Development Seminar', 0, 'Core'),
-- Required Mathematics Courses
('MATH 180', 'Calculus I', 4, 'Core Math'),
('MATH 181', 'Calculus II', 4, 'Core Math'),
('MATH 210', 'Calculus III', 3, 'Core Math'),
-- Science Electives
('BIOS 110', 'Biology of Cells and Organisms', 4, 'Science Elective'),
('BIOS 120', 'Biology of Populations and Communities', 4, 'Science Elective'),
('CHEM 122', 'Matter and Energy', 3, 'Science Elective'),
('CHEM 123', 'Foundations of Chemical Inquiry I', 1, 'Science Elective'),
('CHEM 116', 'Honors and Majors General and Analytical Chemistry I', 5, 'Science Elective'),
('CHEM 124', 'Chemical Dynamics', 3, 'Science Elective'),
('CHEM 125', 'Foundations of Chemical Inquiry II', 2, 'Science Elective'),
('CHEM 118', 'Honors and Majors General and Analytical Chemistry II', 5, 'Science Elective'),
('PHYS 141', 'General Physics I (Mechanics)', 4, 'Science Elective'),
('PHYS 142', 'General Physics II (Electricity and Magnetism)', 4, 'Science Elective'),
('EAES 101', 'Global Environmental Change', 4, 'Science Elective'),
('EAES 111', 'Earth, Energy, and the Environment', 4, 'Science Elective'),
-- Technical Electives
('CS 411', 'Artificial Intelligence I', 3, 'Technical Elective'),
('CS 412', 'Introduction to Machine Learning', 3, 'Technical Elective'),
('CS 418', 'Introduction to Data Science', 3, 'Technical Elective'),
('CS 422', 'User Interface Design and Programming', 3, 'Technical Elective'),
('CS 425', 'Computer Graphics I', 3, 'Technical Elective'),
('CS 440', 'Software Engineering I', 3, 'Technical Elective'),
('CS 441', 'Engineering Distributed Objects for Cloud Computing', 3, 'Technical Elective'),
('CS 442', 'Human-Computer Interaction', 3, 'Technical Elective'),
('CS 450', 'Introduction to Networking', 3, 'Technical Elective'),
('CS 461', 'Computer Systems Design', 3, 'Technical Elective'),
('CS 463', 'Computer Security I', 3, 'Technical Elective'),
('CS 466', 'Advanced Computer Architecture', 3, 'Technical Elective'),
('CS 473', 'Compiler Design', 3, 'Technical Elective'),
('CS 474', 'Object-Oriented Languages and Environments', 3, 'Technical Elective'),
('CS 476', 'Programming Language Design', 3, 'Technical Elective'),
('CS 478', 'Software Development for Mobile Platforms', 3, 'Technical Elective'),
('CS 480', 'Database Systems', 3, 'Technical Elective'),
('CS 481', 'Introduction to Natural Language Processing', 3, 'Technical Elective'),
('CS 482', 'Information Retrieval', 3, 'Technical Elective'),
('CS 484', 'Secure Web Application Development', 3, 'Technical Elective'),
('CS 485', 'Network Security', 3, 'Technical Elective'),
('CS 486', 'Secure Operating System Design and Implementation', 3, 'Technical Elective'),
('CS 487', 'Building Secure Computer Systems', 3, 'Technical Elective'),
('CS 488', 'Introduction to Cryptography', 3, 'Technical Elective'),
('CS 489', 'Human Augmentics', 3, 'Technical Elective'),
-- General Education Courses - Analyzing the Natural World
('ANTH 102', 'Introduction to Archaeology', 4, 'Gen Ed'),
('ANTH 105', 'Human Evolution', 4, 'Gen Ed'),
('ANTH 238', 'Biology of Women', 3, 'Gen Ed'),
('BIOS 104', 'Biology for Non-majors', 4, 'Gen Ed'),
('CHE 150', 'Climate Engineering for Global Warming', 3, 'Gen Ed'),
('CHEM 100', 'Chemistry and Life', 5, 'Gen Ed'),
('CHEM 105', 'Chemistry and the Molecular Human: An Inquiry Perspective', 4, 'Gen Ed'),
('CHEM 115', 'Comprehensive General and Organic Chemistry', 5, 'Gen Ed'),
('CHEM 130', 'Survey of Organic and Biochemistry', 5, 'Gen Ed'),
('CS 100', 'Discovering Computer Science', 3, 'Gen Ed'),
('DHD 206', 'Disability, Inclusive Cities, and Environmental Accessibility', 3, 'Gen Ed'),
('EAES 105', 'Climate, Contamination, and Chicago', 2, 'Gen Ed'),
('EAES 200', 'Field Work in Missouri', 2, 'Gen Ed'),
('EAES 203', 'The Science and Rhetorics of Climate Change', 3, 'Gen Ed'),
('ECON 106', 'Tobacconomics', 3, 'Gen Ed'),
('ECE 115', 'Introduction to Electrical and Computer Engineering', 4, 'Gen Ed'),
('HON 130', 'Honors Core in Analyzing the Natural World and Understanding the Individual and Society', 3, 'Gen Ed'),
('HON 131', 'Honors Core in Analyzing the Natural World and Understanding the Past', 3, 'Gen Ed'),
('HON 132', 'Honors Core in Analyzing the Natural World and Understanding the Creative Arts', 3, 'Gen Ed'),
('HON 133', 'Honors Core in Analyzing the Natural World and Exploring World Cultures', 3, 'Gen Ed'),
('HON 134', 'Honors Core in Analyzing the Natural World and Understanding U.S. Society', 3, 'Gen Ed'),
('HON 145', 'Honors Core in Analyzing the Natural World', 3, 'Gen Ed'),
('HN 196', 'Nutrition', 3, 'Gen Ed'),
('KN 152', 'Introduction to Exercise Physiology and Health', 3, 'Gen Ed'),
('MCS 160', 'Introduction to Computer Science', 4, 'Gen Ed'),
('MATH 125', 'Elementary Linear Algebra', 5, 'Gen Ed'),
('MATH 160', 'Finite Mathematics for Business', 5, 'Gen Ed'),
('MATH 165', 'Calculus for Business', 5, 'Gen Ed'),
('MATH 170', 'Calculus for the Life Sciences', 4, 'Gen Ed'),
('MUS 116', 'The Science and History of Sound in the Arts', 3, 'Gen Ed'),
('NATS 105', 'Physical Systems in Earth and Space Science', 4, 'Gen Ed'),
('NATS 106', 'Chemical and Biological Systems', 4, 'Gen Ed'),
('PHIL 102', 'Introductory Logic', 3, 'Gen Ed'),
('PHIL 105', 'Science and Philosophy', 3, 'Gen Ed'),
('PHYS 112', 'Astronomy and the Universe', 4, 'Gen Ed'),
('PHYS 116', 'Energy for Future Decision-Makers', 3, 'Gen Ed'),
('PHYS 118', 'Physics in Modern Medicine', 3, 'Gen Ed'),
('PHYS 131', 'Introductory Physics for Life Sciences I', 4, 'Gen Ed'),
('PHYS 132', 'Introductory Physics for Life Sciences II', 4, 'Gen Ed'),
('PUBH 120', 'Public Health and the Study of Disease and Epidemics', 3, 'Gen Ed'),
-- General Education Courses - Understanding the Individual and Society
('ANTH 101', 'World Cultures: Introduction to Social Anthropology', 3, 'Gen Ed'),
('ANTH 215', 'Anthropology of Religion', 3, 'Gen Ed'),
('ANTH 216', 'Medicine, Culture, and Society', 3, 'Gen Ed'),
('ANTH 218', 'Anthropology of Children and Childhood', 3, 'Gen Ed'),
('ANTH 273', 'Ethnography of Southeast Asia', 3, 'Gen Ed'),
('ANTH 277', 'Ethnography of Meso-America', 3, 'Gen Ed'),
('ANTH 279', 'South Asian Cultures and Societies', 3, 'Gen Ed'),
('ARCH 200', 'Architecture and Society', 4, 'Gen Ed'),
('ART 110', 'Introduction to Art Education', 4, 'Gen Ed'),
('ART 290', 'Art and Resistance: Socially Engaged Art', 4, 'Gen Ed'),
('AH 101', 'The Naked and the Nude: Studies in Visual Literacy', 3, 'Gen Ed'),
('AH 180', 'Intro to Museum & Exhibition', 3, 'Gen Ed'),
('BLST 100', 'Introduction to Black Studies', 3, 'Gen Ed'),
('BLST 103', 'Black Politics and Culture in the United States', 3, 'Gen Ed'),
('BLST 104', 'Race, Place, and Schooling: Black Americans and Education', 3, 'Gen Ed'),
('BLST 207', 'Racism: Global Perspectives', 3, 'Gen Ed'),
('BLST 263', 'Black Intellectual History', 3, 'Gen Ed'),
('BLST 271', 'Race and the Politics of Incarceration', 3, 'Gen Ed'),
('BLST 272', 'Race, Gender, and Sexuality', 3, 'Gen Ed'),
('CL 208', 'Classical Mythology', 3, 'Gen Ed'),
('COMM 100', 'Fundamentals of Human Communication', 3, 'Gen Ed'),
('COMM 101', 'Introduction to Communication', 3, 'Gen Ed'),
('COMM 102', 'Introduction to Interpersonal Communication', 3, 'Gen Ed'),
('COMM 103', 'Introduction to Media', 3, 'Gen Ed'),
('COMM 140', 'Fundamentals of Social Media and Communication', 3, 'Gen Ed'),
('DLG 220', 'Intergroup Dialogue', 3, 'Gen Ed'),
('DHD 101', 'Disability in U.S. Society', 3, 'Gen Ed'),
('DHD 201', 'Disability, Rights, and Culture', 3, 'Gen Ed'),
('DHD 202', 'Disability, Health, and Society', 3, 'Gen Ed'),
('DHD 205', 'Disability, Race, Class and Gender', 3, 'Gen Ed'),
('ECON 111', 'Freakonomics', 3, 'Gen Ed'),
('ECON 120', 'Principles of Microeconomics', 4, 'Gen Ed'),
('ECON 121', 'Principles of Macroeconomics', 4, 'Gen Ed'),
('ED 100', 'Introduction to Urban Education', 3, 'Gen Ed'),
('ED 101', 'Critical Literacies in a Digital Democracy', 3, 'Gen Ed'),
('ED 135', 'Child and Youth Policies in Urban America', 3, 'Gen Ed'),
('ED 205', 'Introduction to Race, Ethnicity, and Education', 3, 'Gen Ed'),
('EPSY 100', 'Introduction to Human Development and Learning', 3, 'Gen Ed'),
('EPSY 160', 'Games, Learning, and Society', 3, 'Gen Ed'),
('ENGL 135', 'Understanding Popular Genres and Culture', 3, 'Gen Ed'),
('ENGL 154', 'Understanding Rhetoric', 3, 'Gen Ed'),
('ENGL 230', 'Introduction to Film and Culture', 3, 'Gen Ed'),
('ENGL 245', 'Introduction to Gender, Sexuality and Literature', 3, 'Gen Ed'),
('ENGL 247', 'Women and Literature', 3, 'Gen Ed'),
('ENGL 253', 'Environmental Rhetoric', 3, 'Gen Ed'),
('ENTR 200', 'Survey of Entrepreneurship', 3, 'Gen Ed'),
('FIN 250', 'Personal Finance', 3, 'Gen Ed'),
('GWS 101', 'Gender in Everyday Life', 3, 'Gen Ed'),
('GWS 102', 'Global Perspectives on Women and Gender', 3, 'Gen Ed'),
('GWS 204', 'Gender and Popular Culture', 3, 'Gen Ed'),
('GEOG 161', 'Introduction to Economic Geography', 3, 'Gen Ed'),
('GER 120', 'Study of Gender, Class, and Political Issues in German Texts', 3, 'Gen Ed'),
('GLAS 120', 'Introduction to Asian American Studies', 3, 'Gen Ed'),
('GLAS 210', 'Asian American Histories', 3, 'Gen Ed'),
('GLAS 230', 'Cultural Politics of Asian American Food', 3, 'Gen Ed'),
('GLAS 250', 'Critical Issues in Community Engagement', 3, 'Gen Ed'),
('PSCH 100', 'Introduction to Psychology', 4, 'Gen Ed'),
('PSCH 210', 'Theories of Personality', 3, 'Gen Ed'),
('PSCH 231', 'Community Psychology', 3, 'Gen Ed'),
('PSCH 270', 'Introduction to Psychological and Behavioral Disorders', 3, 'Gen Ed'),
('PPOL 100', 'Individual Action and Democratic Citizenship', 3, 'Gen Ed'),
('PPOL 101', 'Contemporary Issues in Public Policy', 3, 'Gen Ed'),
('PUBH 100', 'Health and the Public', 3, 'Gen Ed'),
('SOC 100', 'Introduction to Sociology', 3, 'Gen Ed'),
('SOC 105', 'Social Problems', 3, 'Gen Ed'),
('SOC 215', 'Sociology of Childhood and Youth', 3, 'Gen Ed'),
('SOC 224', 'Gender and Society', 3, 'Gen Ed'),
('SOC 225', 'Racial and Ethnic Groups', 3, 'Gen Ed'),
('SOC 228', 'Sociology of Asia and Asian Americans', 3, 'Gen Ed'),
('SOC 229', 'Sociology of Latinos', 3, 'Gen Ed'),
('SOC 241', 'Social Inequalities', 3, 'Gen Ed'),
('SOC 244', 'Sociology of Work', 3, 'Gen Ed'),
('SOC 245', 'Marriage and Family', 3, 'Gen Ed'),
('SOC 246', 'Sociology of Religion', 3, 'Gen Ed'),
('SOC 251', 'Health and Medicine', 3, 'Gen Ed'),
('SOC 276', 'Urban Sociology', 3, 'Gen Ed'),
-- General Education Courses - Understanding the Past
('ANTH 100', 'The Human Adventure', 3, 'Gen Ed'),
('ARAB 250', 'The Heritage of Muslim Iberia', 3, 'Gen Ed'),
('ARCH 210', 'Architecture as Archetype: Explorations of the City and Its Forms', 3, 'Gen Ed'),
('AH 122', 'History of Chicago Architecture', 3, 'Gen Ed'),
('AH 130', 'Photography in History', 3, 'Gen Ed'),
('AH 150', 'Art and Money', 3, 'Gen Ed'),
('AH 209', 'Near Eastern Art and Archaeology', 3, 'Gen Ed'),
('AH 210', 'Ancient Egyptian Art and Archaeology', 3, 'Gen Ed'),
('AH 259', 'Art in the Age of Enlightenment and Revolution', 3, 'Gen Ed'),
('BLST 101', 'Introduction to Black Diaspora Studies', 3, 'Gen Ed'),
('BLST 125', 'Black Religious Traditions', 3, 'Gen Ed'),
('BLST 246', 'Black Lives in Historical Context', 3, 'Gen Ed'),
('BLST 247', 'African American History to 1877', 3, 'Gen Ed'),
('BLST 248', 'African American History since 1877', 3, 'Gen Ed'),
('BLST 249', 'Black Freedom Movements in the U.S.', 3, 'Gen Ed'),
('CL 100', 'Greek Civilization', 3, 'Gen Ed'),
('CL 101', 'Roman Civilization', 3, 'Gen Ed'),
('CL 102', 'Introduction to Classical Literature', 3, 'Gen Ed'),
('CL 103', 'Introduction to Classical and Mediterranean Archaeology', 3, 'Gen Ed'),
('CL 204', 'Greek Art and Archaeology', 3, 'Gen Ed'),
('CL 205', 'Roman Art and Archaeology', 3, 'Gen Ed'),
('CL 218', 'Pompeii: Everyday Life in a Roman Town', 3, 'Gen Ed'),
('CL 250', 'Greek and Roman Epic Poetry', 3, 'Gen Ed'),
('CL 251', 'Greek Tragedy', 3, 'Gen Ed'),
('CL 252', 'Greek and Roman Comedy', 3, 'Gen Ed'),
('CL 253', 'Roman Satire and Rhetoric', 3, 'Gen Ed'),
('ENGL 208', 'English Studies I: Beginnings to the 17th Century', 3, 'Gen Ed'),
('ENGL 213', 'Introduction to Shakespeare', 3, 'Gen Ed'),
('GER 125', 'Diaspora, Exile, Genocide: Aspects of the European Jewish Experience in Literature and Film', 3, 'Gen Ed'),
('GER 219', 'Princesses and Storytellers: Fairy Tales by the Brothers Grimm and Their Cultural Afterlives', 3, 'Gen Ed'),
('HIST 100', 'Western Civilization to 1648', 3, 'Gen Ed'),
('HIST 101', 'Western Civilization Since 1648', 3, 'Gen Ed'),
('HIST 103', 'Early America: From Colonization to Civil War and Reconstruction', 3, 'Gen Ed'),
('HIST 104', 'Modern America: From Industrialization to Globalization', 3, 'Gen Ed'),
('HIST 105', 'Global Transformations and the Rise of the West Since 1000', 3, 'Gen Ed'),
('HIST 106', 'The World Since 1400: Converging Worlds, New Circulations', 3, 'Gen Ed'),
('HIST 109', 'East Asian Civilization: Ancient China', 3, 'Gen Ed'),
('HIST 117', 'Understanding the Holocaust', 3, 'Gen Ed'),
('HIST 137', 'Russia in War and Revolution, 1904-1922', 3, 'Gen Ed'),
('HIST 161', 'Introduction to Latin American History', 3, 'Gen Ed'),
('HIST 170', 'The Ottoman Empire', 3, 'Gen Ed'),
('HIST 177', 'Middle Eastern Civilization', 3, 'Gen Ed'),
('HIST 202', 'Ancient Greece', 3, 'Gen Ed'),
('HIST 203', 'Ancient Rome', 3, 'Gen Ed'),
('HIST 208', 'History of Science in a Global Context', 3, 'Gen Ed'),
('HIST 211', 'The Dawn of European Modernity, 1500-1715', 3, 'Gen Ed'),
('HIST 214', 'Twentieth-Century Europe', 3, 'Gen Ed'),
('HIST 220', 'Modern Germany, 1848 to the Present', 3, 'Gen Ed'),
('HIST 221', 'The Atlantic Slave Trade', 3, 'Gen Ed'),
('HIST 224', 'France: 1500 to 1715', 3, 'Gen Ed'),
('HIST 233', 'East Central Europe and the Balkans: From Empires to Nation-States', 3, 'Gen Ed'),
('HIST 237', 'The Russian Empire in the Modern Period: History, Culture and the Challenges of Diversity', 3, 'Gen Ed'),
('HON 120', 'Honors Core in Understanding Individual and Society and Understanding the Past', 3, 'Gen Ed'),
('HON 125', 'Honors Core in Understanding the Past and Exploring World Cultures', 3, 'Gen Ed'),
('HON 141', 'Honors Core in Understanding the Past', 3, 'Gen Ed'),
('ITAL 230', 'Italian and Italian American Culture and Civilization', 3, 'Gen Ed'),
('JST 102', 'Introduction to Jewish History', 3, 'Gen Ed'),
('LALS 101', 'Introduction to Latin American Studies', 3, 'Gen Ed'),
('HIST 293', 'The Gilded and the Gritty: Power, Culture, and the Making of 20th-century America', 3, 'Gen Ed'),
('THTR 101', 'Theatre History I: Premodern Drama', 3, 'Gen Ed'),
('THTR 103', 'History of Chicago Theatre Past and Present', 3, 'Gen Ed'),
('THTR 159', 'Fashion and Furniture: History of Cultural Influences from Gothic to Atomic', 3, 'Gen Ed'),
-- General Education Courses - Understanding the Creative Arts
('ARAB 270', 'The Reel Arab', 3, 'Gen Ed'),
('ART 112', 'Introduction to Drawing', 4, 'Gen Ed'),
('ART 130', 'Introduction to Painting + Color', 4, 'Gen Ed'),
('ART 140', 'Introduction to Sculpture', 4, 'Gen Ed'),
('ART 150', 'Introduction to New Media Arts', 4, 'Gen Ed'),
('ART 151', 'Introduction to Creative Coding in New Media Arts', 4, 'Gen Ed'),
('ART 160', 'Introduction to Digital Photography', 4, 'Gen Ed'),
('ART 170', 'Introduction to Filmmaking', 4, 'Gen Ed'),
('ART 190', 'Introduction to Socially Engaged Art', 4, 'Gen Ed'),
('AH 100', 'Introduction to Art and Art History', 3, 'Gen Ed'),
('AH 110', 'World History of Art and the Built Environment I', 4, 'Gen Ed'),
('AH 111', 'World History of Art and the Built Environment II', 4, 'Gen Ed'),
('AH 125', 'Introduction to the Art and Architecture of Asia', 3, 'Gen Ed'),
('AH 140', 'World Architecture, Climate, and Ecology: An Alternative History', 3, 'Gen Ed'),
('AH 160', 'Trends in International Contemporary Art Since 1960', 3, 'Gen Ed'),
('AH 172', 'Visual Culture of the Ancient Americas', 3, 'Gen Ed'),
('AH 201', 'Reading and Writing Art Criticism', 3, 'Gen Ed'),
('AH 211', 'History of Urbanism', 3, 'Gen Ed'),
('AH 219', 'Art and Architecture of East Asia', 3, 'Gen Ed'),
('AH 220', 'Buddhist Art and Architecture', 3, 'Gen Ed'),
('AH 223', 'Baroque Architecture', 3, 'Gen Ed'),
('AH 230', 'History of Photography I: 1820-1920', 3, 'Gen Ed'),
('AH 231', 'History of Photography II: 1900 to Present', 3, 'Gen Ed'),
('AH 242', 'Early Christian and Byzantine Art and Architecture', 3, 'Gen Ed'),
('AH 243', 'Medieval Art and Architecture', 3, 'Gen Ed'),
('AH 244', 'Islamic Art and Architecture', 3, 'Gen Ed'),
('AH 250', 'Italian Renaissance Art', 3, 'Gen Ed'),
('AH 251', 'Northern Renaissance Art and Architecture', 3, 'Gen Ed'),
('AH 252', 'Art of the Baroque and Rococo', 3, 'Gen Ed'),
('AH 260', 'European Art from 1750 to 1900', 3, 'Gen Ed'),
('AH 261', 'European and American Art from 1900 to the Present', 3, 'Gen Ed'),
('AH 262', 'American Art to 1945', 3, 'Gen Ed'),
('AH 263', 'Latin American Colonial Art', 3, 'Gen Ed'),
('AH 264', 'African American Art', 3, 'Gen Ed'),
('AH 265', 'History of Performance Art 1900 - Present', 3, 'Gen Ed'),
('AH 270', 'African Art', 3, 'Gen Ed'),
('AH 271', 'Native American Art', 3, 'Gen Ed'),
('AH 273', 'Visual Culture of the Ancient Andes', 3, 'Gen Ed'),
('AH 274', 'Visual Culture of Ancient Mesoamerica', 3, 'Gen Ed'),
('AH 275', 'South Asian Visual Cultures', 3, 'Gen Ed'),
('BLST 105', 'Black Film, 1900 - Present: Images, Individuals and Ideas on Screen', 3, 'Gen Ed'),
('BLST 110', 'Introduction to African American Literature, 1760-1910', 3, 'Gen Ed'),
('BLST 111', 'Introduction to African American Literature Since 1910', 3, 'Gen Ed'),
('BLST 250', 'Comparative Black Literatures', 3, 'Gen Ed'),
('BLST 262', 'Black Cultural Studies', 3, 'Gen Ed'),
('CEES 208', 'Central and Eastern European Cinema', 3, 'Gen Ed'),
('CEES 246', 'European Avant-Garde', 3, 'Gen Ed'),
('CEES 250', 'Eurasian Cinema: Film and Media Across Borders', 4, 'Gen Ed'),
('CL 297', 'Studies in the Classical Tradition', 3, 'Gen Ed'),
('CME 111', 'The Art of Structural Form', 3, 'Gen Ed'),
('DHD 102', 'Disability in American Film', 3, 'Gen Ed'),
('DHD 204', 'Disability in the Humanities', 3, 'Gen Ed'),
('ENGL 101', 'Understanding Literature and Culture', 3, 'Gen Ed'),
('ENGL 103', 'Understanding Poetry', 3, 'Gen Ed'),
('ENGL 104', 'Understanding Drama', 3, 'Gen Ed'),
('ENGL 105', 'Understanding Fiction', 3, 'Gen Ed'),
('ENGL 123', 'Introduction to Asian American Literature', 3, 'Gen Ed'),
('ENGL 131', 'Understanding Moving Image Arts', 3, 'Gen Ed'),
('ENGL 132', 'Understanding Film', 3, 'Gen Ed'),
('ENGL 175', 'Understanding the Bible as Literature', 3, 'Gen Ed'),
('ENGL 207', 'Interpretation and Critical Analysis', 3, 'Gen Ed'),
('ENGL 209', 'English Studies II: 17th Century to Today', 3, 'Gen Ed'),
('ENGL 223', 'Introduction to Colonial and Postcolonial Literature', 3, 'Gen Ed'),
('ENGL 232', 'History of Film I: 1890 to World War II', 3, 'Gen Ed'),
('ENGL 233', 'History of Film II: World War II to the Present', 3, 'Gen Ed'),
('ENGL 236', 'Young Adult Fiction', 3, 'Gen Ed'),
('ENGL 237', 'Graphic Novels', 3, 'Gen Ed'),
('ENGL 238', 'Speculative Fiction, Sci-Fi and Fantasy', 3, 'Gen Ed'),
('ENGL 251', 'Literature and Environment', 3, 'Gen Ed'),
('ENGL 264', 'Introduction to Native American Literatures', 3, 'Gen Ed'),
('ENGL 267', 'Introduction to U.S. Latinx Literature', 3, 'Gen Ed'),
('ENGL 269', 'Introduction to Multiethnic Literatures in the United States', 3, 'Gen Ed'),
('ENGL 290', 'Introduction to the Writing of Poetry', 3, 'Gen Ed'),
('ENGL 291', 'Introduction to the Writing of Fiction', 3, 'Gen Ed'),
('ENGL 292', 'Introduction to the Writing of Nonfiction Prose', 3, 'Gen Ed'),
('FR 191', 'African and Caribbean Francophone Literature in Translation', 3, 'Gen Ed'),
('FR 295', 'Science Fiction and Fantasy in the French-Speaking World', 3, 'Gen Ed'),
('FR 297', 'Paris in Literature, Film, and Culture', 3, 'Gen Ed'),
('FR 298', 'French Literature, Drama and/or Film in Translation', 3, 'Gen Ed'),
('GER 100', 'Introduction to Germanic Cultures and Literatures', 3, 'Gen Ed'),
('GER 122', 'Minority Perspectives in the Germanic Context', 3, 'Gen Ed'),
('GER 123', 'Introduction to Yiddish Culture and Literature', 3, 'Gen Ed'),
('GER 217', 'Introduction to German Cinema', 4, 'Gen Ed'),
('GLAS 223', 'Global Hip-hop and Asian Diasporas', 3, 'Gen Ed'),
('HON 121', 'Honors Core in Understanding Individual and Society and Understanding Creative Arts', 3, 'Gen Ed'),
('HON 124', 'Honors Core in Understanding the Past and Understanding the Creative Arts', 3, 'Gen Ed'),
('HON 127', 'Honors Core in Understanding the Creative Arts and Exploring World Cultures', 3, 'Gen Ed'),
('HON 128', 'Honors Core in Understanding the Creative Arts and Understanding U.S. Society', 3, 'Gen Ed'),
('HON 142', 'Honors Core in Understanding the Creative Arts', 3, 'Gen Ed'),
('IDEA 110', 'Creativity and Innovation in Design and Arts', 4, 'Gen Ed'),
('ITAL 280', 'Italian and Italian American Cinema', 3, 'Gen Ed'),
('ITAL 293', "Dante's Divine Comedy", 3, 'Gen Ed'),
('LALS 109', 'Introduction to Latino Cultures', 3, 'Gen Ed'),
('LALS 110', 'Introduction to Latin American Cultures', 3, 'Gen Ed'),
('LALS 260', 'Indigenous Storytelling in Latin America', 3, 'Gen Ed'),
('LALS 278', 'Latin American/Latino Film Studies', 4, 'Gen Ed'),
('LALS 295', 'Latino Literary Studies', 3, 'Gen Ed'),
('LCSL 207', 'European Cinema', 3, 'Gen Ed'),
('LCSL 250', 'Introduction to Comparative Cultural Studies', 3, 'Gen Ed'),
('LCSL 275', 'Encoding Text Cultures: Reading with Computers in Text-based Humanities', 3, 'Gen Ed'),
('LITH 130', 'Lithuanian Prose Fiction in International Context', 3, 'Gen Ed'),
('MUS 100', 'Introduction to Music I', 3, 'Gen Ed'),
('MUS 107', 'Fundamentals of Music Theory', 3, 'Gen Ed'),
('MUS 113', 'Art Song', 3, 'Gen Ed'),
('MUS 114', 'Jazz History', 3, 'Gen Ed'),
('MUS 115', 'Opera', 3, 'Gen Ed'),
('MUS 117', 'Music for Symphony Orchestra', 3, 'Gen Ed'),
('MUS 118', 'American Popular Music since 1850', 3, 'Gen Ed'),
('MUS 119', 'Music for the Piano', 3, 'Gen Ed'),
('MUS 127', 'Latin American Music', 3, 'Gen Ed'),
('MUS 227', 'Music Cultures of the World', 3, 'Gen Ed'),
('MUS 240', 'Music, Gender and Culture', 3, 'Gen Ed'),
('PHIL 107', 'What is Art?', 3, 'Gen Ed'),
('POL 120', 'The Polish Short Story in Translation', 3, 'Gen Ed'),
('POL 130', 'Masterworks of Polish Literature in Translation', 3, 'Gen Ed'),
('POL 140', 'Polish Drama in Translation', 3, 'Gen Ed'),
('POL 150', 'Introduction to Polish Cinema', 3, 'Gen Ed'),
('POL 220', 'Modern Polish-Jewish Culture and Literatures', 3, 'Gen Ed'),
('RUSS 120', 'The Russian Short Story in Translation', 3, 'Gen Ed'),
('RUSS 130', 'Masterpieces of Russian Literature in Translation', 3, 'Gen Ed'),
('RUSS 140', 'Understanding the Body: Health, Gender, and Disability in Russian Culture', 3, 'Gen Ed'),
('RUSS 150', 'Introduction to Russian Cinema', 3, 'Gen Ed'),
('RUSS 241', 'Dostoyevsky', 3, 'Gen Ed'),
('RUSS 242', 'Tolstoy', 3, 'Gen Ed'),
('RUSS 244', 'Women in Russian Literature', 3, 'Gen Ed'),
('RUSS 247', 'Literature and Fantasy in Russia', 3, 'Gen Ed'),
('RUSS 248', 'Russian Visual and Material Culture', 3, 'Gen Ed'),
('SPAN 226', 'Early Modern Spanish and Colonial Latin American Literature and Culture in Translation', 3, 'Gen Ed'),
('SPED 201', "Children's Literature and Disabilities", 3, 'Gen Ed'),
('THTR 102', 'Introduction to Theatre: A Collaborative Art', 3, 'Gen Ed'),
('THTR 105', 'Introduction to American Musical Theatre', 3, 'Gen Ed'),
('THTR 201', 'Theatre History II: Modern Theatre', 3, 'Gen Ed'),
('THTR 245', 'East Asian Theatre', 3, 'Gen Ed'),
-- General Education Courses - Exploring World Cultures
('ANTH 207', 'Asian Cities: Urban Cultures of the Global South', 3, 'Gen Ed'),
('ANTH 208', 'Virtual Lives: Science, Technology, and Culture', 3, 'Gen Ed'),
('ANTH 219', 'Anthropology of Globalization', 3, 'Gen Ed'),
('ARAB 105', 'Modern Arab Culture', 3, 'Gen Ed'),
('ARAB 230', 'Arabic Literature in Translation', 3, 'Gen Ed'),
('BLST 221', 'The Atlantic Slave Trade: Violence, Exploitation, Resistance', 3, 'Gen Ed'),
('DHD 203', 'Disability in World Cultures', 3, 'Gen Ed'),
('GWS 255', 'Introduction to Middle East and Muslim Feminisms', 3, 'Gen Ed'),
('GWS 262', 'Constructions of Gender, Race, Health, and Human Rights', 3, 'Gen Ed'),
('GEOG 203', 'Human Geography of Latin America including the Caribbean Region', 3, 'Gen Ed'),
('GLAS 100', 'Introduction to Global Asian Studies', 3, 'Gen Ed'),
('GLAS 201', 'Asian Markets, Corporations, and Social Justice', 3, 'Gen Ed'),
('GLAS 229', 'Introduction to Asian Film', 3, 'Gen Ed'),
('GLAS 242', 'Introduction to Arab American Studies', 3, 'Gen Ed'),
('GLAS 244', 'Arab and Asian Connections in the U.S. and Globally', 3, 'Gen Ed'),
('GLAS 248', 'Afro Asian Solidarities', 3, 'Gen Ed'),
('GLAS 270', 'Topics in Asian Cultures and Societies', 3, 'Gen Ed'),
('GKM 105', 'Modern Greek Culture', 3, 'Gen Ed'),
('GKM 203', 'Modern Greek Authors in Translation', 3, 'Gen Ed'),
('HIST 225', 'The Age of Revolution in France: 1715-1848', 3, 'Gen Ed'),
('HIST 226', 'France and the World, 1848-present', 3, 'Gen Ed'),
('HIST 236', 'Russia Between Europe and Asia: Eurasian Spaces and Peoples in the Premodern Era', 3, 'Gen Ed'),
('HIST 241', 'Precolonial Africa in World History', 3, 'Gen Ed'),
('HIST 242', 'History of Modern Africa', 3, 'Gen Ed'),
('HIST 261', 'Latin America to 1850', 3, 'Gen Ed'),
('HIST 262', 'Latin America Since 1850', 3, 'Gen Ed'),
('HIST 264', 'The Pacific Rim in Modern History', 3, 'Gen Ed'),
('HIST 266', 'Modern Mexico', 3, 'Gen Ed'),
('HIST 271', 'Late Imperial China: 1500 to 1911', 3, 'Gen Ed'),
('HIST 272', 'China Since 1911', 3, 'Gen Ed'),
('HIST 275', 'History of South Asia to 1857', 3, 'Gen Ed'),
('HIST 276', 'Modern South Asia, 1857 to the Present', 3, 'Gen Ed'),
('HIST 277', 'The Middle East to 1258', 3, 'Gen Ed'),
('HIST 278', 'The Middle East Since 1258', 3, 'Gen Ed'),
('HON 122', 'Honors Core in Understanding Individual and Society and Exploring World Cultures', 3, 'Gen Ed'),
('HON 129', 'Honors Core in Exploring World Cultures and Understanding U.S. Society', 3, 'Gen Ed'),
('HON 143', 'Honors Core in Exploring World Cultures', 3, 'Gen Ed'),
('HN 202', 'Culture and Food', 2, 'Gen Ed'),
('JST 103', 'Introduction to Israel Studies', 3, 'Gen Ed'),
('JST 203', 'Israel Film: Aspects of History, Life, and Culture', 3, 'Gen Ed'),
('KOR 130', 'Understanding Korean History, Culture and Society through Contemporary Korean Films', 3, 'Gen Ed'),
('KOR 230', 'Korean Popular Culture in a Global World', 3, 'Gen Ed'),
('LALS 104', 'Introduction to Puerto Rican Studies', 3, 'Gen Ed'),
('LALS 105', 'Introduction to Mexican Studies', 3, 'Gen Ed'),
('LALS 107', 'Introduction to Nahua Studies', 3, 'Gen Ed'),
('LALS 108', 'Indigenous Culture Change in Latin America', 3, 'Gen Ed'),
('LALS 220', 'Latin American Cities in a Global Context: Environment, Employment, and Housing', 3, 'Gen Ed'),
('LALS 269', 'Latin American Environmental Studies', 3, 'Gen Ed'),
('LALS 275', 'Gender in Latin America', 3, 'Gen Ed'),
('LING 170', 'Languages of the World', 3, 'Gen Ed'),
('LITH 115', 'Lithuanian Culture', 3, 'Gen Ed'),
('NAST 113', 'Native American Studies: Sovereignty', 3, 'Gen Ed'),
('PHIL 240', 'Philosophy and Revelation: Jewish and Christian Perspectives', 3, 'Gen Ed'),
('POL 115', 'Introduction to Polish Culture', 3, 'Gen Ed'),
('POLS 184', 'Introduction to International Relations', 3, 'Gen Ed'),
('POLS 231', 'Politics and Society of China', 3, 'Gen Ed'),
('POLS 232', 'Politics in Korea', 3, 'Gen Ed'),
('POLS 243', 'Politics and Government of the Middle East', 3, 'Gen Ed'),
('PPOL 232', 'International Development Policy', 3, 'Gen Ed'),
('PUBH 110', 'Public Health and Global Societies', 3, 'Gen Ed'),
('RELS 101', 'Introduction to World Religions', 3, 'Gen Ed'),
('RELS 130', 'Introduction to Islam', 3, 'Gen Ed'),
('RELS 230', 'Topics in Islam', 3, 'Gen Ed'),
('RELS 250', 'Eastern and Western Philosophies of Religion', 3, 'Gen Ed'),
('RUSS 115', 'Russian Culture Before the Revolution', 3, 'Gen Ed'),
('RUSS 116', 'Russian Culture: The Soviet Period', 3, 'Gen Ed'),
('SOC 268', 'Introduction to Comparative Sociology', 3, 'Gen Ed'),
('SPAN 192', 'Latin American Women Writers in Translation', 3, 'Gen Ed'),
('SPAN 225', 'Spanish and Latin American Culture through Literature and Film', 3, 'Gen Ed'),
('SPED 202', 'International Perspectives: Inclusive Education and Schooling', 3, 'Gen Ed'),
('US 100', 'Concepts in Geography', 3, 'Gen Ed'),
('US 220', 'Latin American Cities in a Global Context: Environment, Employment, and Housing', 3, 'Gen Ed'),
-- General Education Courses - Understanding U.S. Society
('BLST 265', 'Harlem Renaissance', 3, 'Gen Ed'),
('CST 150', 'Catholicism in U.S. History', 3, 'Gen Ed'),
('CME 112', 'Evolution of Infrastructure and Society', 3, 'Gen Ed'),
('CLJ 101', 'Introduction to Criminology, Law, and Justice', 3, 'Gen Ed'),
('CLJ 102', 'Foundations of Law and Justice', 3, 'Gen Ed'),
('CLJ 110', 'Rights, Justice and the Law', 3, 'Gen Ed'),
('CLJ 114', 'Race, Class, Gender and the Law', 3, 'Gen Ed'),
('CLJ 120', 'Crime and Society', 3, 'Gen Ed'),
('CLJ 121', 'Violence in Society', 3, 'Gen Ed'),
('CLJ 122', 'Gangs and the Media', 3, 'Gen Ed'),
('CLJ 200', 'Law and Society', 3, 'Gen Ed'),
('ED 200', 'Education Policy Foundations', 3, 'Gen Ed'),
('ED 222', 'Introduction to Gender, Sexuality, and Education', 3, 'Gen Ed'),
('ED 252', 'Contemporary Controversies in U.S. Schools', 3, 'Gen Ed'),
('ED 253', 'Current Debates in Higher Education', 3, 'Gen Ed'),
('ED 258', 'Language Development and Learning in a Diverse Society', 3, 'Gen Ed'),
('ENGL 258', 'The Grammar and Style of Non-Standard Englishes in the U.S.', 3, 'Gen Ed'),
('GLAS 217', 'Introduction to Filipino American Studies', 3, 'Gen Ed'),
('GLAS 252', 'U.S. Racism and Imperialism', 3, 'Gen Ed'),
('GLAS 263', 'Asian American Gender and Sexual Diversity', 3, 'Gen Ed'),
('HIST 240', 'Radicalism in America: From the Revolution to Occupy Wall Street', 3, 'Gen Ed'),
('HIST 245', 'Imagining the American West', 3, 'Gen Ed'),
('HIST 246', 'History of American Capitalism', 3, 'Gen Ed'),
('HIST 249', 'The American Civil War', 3, 'Gen Ed'),
('HIST 252', 'Sexuality in America: Historical Perspectives', 3, 'Gen Ed'),
('HIST 253', 'The Worker in American Life', 3, 'Gen Ed'),
('HIST 255', 'History of Chicago', 3, 'Gen Ed'),
('HIST 256', 'Religion in American History', 3, 'Gen Ed'),
('HIST 259', 'Women and Gender in American History', 3, 'Gen Ed'),
('HIST 267', 'American Intellectual History to 1865', 3, 'Gen Ed'),
('HIST 268', 'American Intellectual History since 1865', 3, 'Gen Ed'),
('HON 123', 'Honors Core in Understanding Individual and Society and Understanding U.S. Society', 3, 'Gen Ed'),
('HON 126', 'Honors Core in Understanding the Past and Understanding U.S. Society', 3, 'Gen Ed'),
('HON 144', 'Honors Core in Understanding U.S. Society', 3, 'Gen Ed'),
('ITAL 270', 'Migration, Society and Identity in the Italian and Italian American Experience', 3, 'Gen Ed'),
('LALS 102', 'Introduction to Latino Studies', 3, 'Gen Ed'),
('LALS 103', 'Introduction to Latino Urban Studies', 3, 'Gen Ed'),
('LALS 276', 'Latinas in the United States', 3, 'Gen Ed'),
('LALS 283', 'Latinos and Politics', 3, 'Gen Ed'),
('LALS 290', 'Mexican-American History', 3, 'Gen Ed'),
('LING 160', 'Language and Society', 3, 'Gen Ed'),
('LING 260', 'Language Acquisition, Language Contact and Bilingualism', 3, 'Gen Ed'),
('PHAR 201', 'Pharmaceutical Care in the US', 3, 'Gen Ed'),
('PHIL 104', 'Introduction to Political Philosophy', 3, 'Gen Ed'),
('PHIL 131', 'Educational Ethics', 3, 'Gen Ed'),
('POLS 101', 'Introduction to American Government and Politics', 3, 'Gen Ed'),
('PPOL 210', 'Introduction to Public Policy', 3, 'Gen Ed'),
('PPOL 212', 'Evidence-Based Public Policy', 3, 'Gen Ed'),
('PPOL 220', 'Introduction to Civic Technology', 3, 'Gen Ed'),
('PPOL 230', 'Nonprofit Organizations and Civil Society', 3, 'Gen Ed'),
('PPOL 231', 'Social Policy and Inequality in the U.S.', 3, 'Gen Ed'),
('PPOL 240', 'Environmental Policy', 3, 'Gen Ed'),
('RELS 256', 'Religion in American History', 3, 'Gen Ed'),
('SJ 201', 'Theories and Practices of Social Justice', 3, 'Gen Ed'),
('SPAN 224', 'Bilingual/Bicultural Hispanic American Writers', 3, 'Gen Ed'),
('US 101', 'Introduction to Urban Studies', 3, 'Gen Ed'),
('US 130', 'Principles of Urban Sustainability', 3, 'Gen Ed'),
('US 202', 'Social Justice and the City', 3, 'Gen Ed'),
('US 230', 'Practices for Sustainable Cities', 3, 'Gen Ed');
